Repository govau/chameleon, pull requests merged in 2018-12, with the labels that each got.

#57 Remove xss sameorigin for localhost
  index.js
Labels: enhancement

#70 Just adjusting some spacing
  src/cli.js
  src/html.js
  src/index.js
  src/settings.js
  src/slack.js
  src/style.js
Labels: enhancement

#71 Fixes #53, removes placeholdit images
  assets/img/100x100.jpg
  assets/img/600x260.jpg
  package-lock.json
  templates/index.html
Labels: enhancement

#74 Add unit test for multiple inputs
  test/unit/index.spec.js
Labels: enhancement, test

#78 [WIP] Simplified previous slack code
  src/index.js
  src/slack.js
Labels: enhancement

#79 Improve slack message
  src/index.js
  src/slack.js
  test/unit/index.spec.js
Labels: enhancement

#82 Fix CF ups
  .deploy/manifest-dev.yml
  .deploy/manifest-prod.yml
Labels: bug, enhancement

#84 Update sass and accordion button
  assets/sass/main.scss
  templates/basic/index.html
Labels: enhancement

#86 Send slack if CF VCAP_SERVICES
  src/index.js
Labels: bug, enhancement

#89 Update formatting, split tests, some spacing
  package-lock.json
  package.json
  src/index.js
  src/slack.js
  src/style.js
  test/unit/html.spec.js
  test/unit/index.spec.js
  test/unit/slack.spec.js
  test/unit/style.spec.js
Labels: enhancement
